### ISSUE TITLE
Darwin: CFFI does not find the readline library

### ISSUE THREAD

**Issue by Davidbhodge** [vindarel/cl-readline#1]
A suggested fix in cl-readline.lisp

(define-foreign-library readline
  (:darwin (:or "libreadline.dylib" ))
  (:unix (:or "libreadline.so.6.3"
              "libreadline.so.6"
              "libreadline.so"))

  (t     (:default "libreadline")))

**Comment by mrkkrp** [comment]
Thank you. If you're using Quicklisp, fixed `cl-readline` will be available next month (Quicklisp distribution is updated monthly).
