### ISSUE TITLE
Support for readline version 7

### ISSUE THREAD

**Issue by rladams** [vindarel/cl-readline#11]
Currently CFFI only looks for readline v6 on load.

My Gentoo system has v7, so that fails.

If I update the library list to include libreadline.so.7 it loads, and the example project for Replic which depends on cl-readline runs as I would expect.

**Comment by vindarel** [comment]
Thanks for the report. 

(Want to author a PR ?)

**Comment by rladams** [comment]
Not a git/github user, and it's a one character change. I'm confident in your ability!

I will keep testing with v7 on my simple scripts and let you know if I encounter anything unusual.

**Comment by ryukinix** [comment]
Thanks for this report as well! I'm having this problems for months at lisp-chat, I forgot to report so sudden got fixed. Pretty nice!
