### ISSUE TITLE
Way to disable echo on readline?

### ISSUE THREAD

**Issue by ryukinix** [vindarel/cl-readline#7]
Just as title say, there is a way to disable echo readline? I want to read the message from the user, but I don't want to print to stdout after the user finish the text (send newline).

This is a awesome binding, thanks for providing that!

**Comment by mrkkrp** [comment]
Sorry, I'm not aware of a way to do this. It's been a while since I worked on this package and in Common Lisp in general. The library was written in end of 2014, beginning of 2015, so right now I have little idea what is going there!

If you find a way to solve this, I'll accept a PR.

**Comment by ryukinix** [comment]
Closed due lack of activity (> year 1).
