### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by vindarel** [vindarel/cl-readline#9]
Hello,

I don't want cl-readline to go into limbos, I'm ready to help maintain or maintain it. I started using a cl-readline-based tool daily and building generalizations on the library ([here](https://github.com/vindarel/replic)), so hopefully my interest will last a bit.

Regards

(context: https://www.reddit.com/r/lisp/comments/7uy75k/im_looking_for_maintainers_for_some_common_lisp/)

**Comment by mrkkrp** [comment]
Thanks! I started repo transfer to your account.

**Comment by vindarel** [comment]
it's done. Well, thank you. I see you found maintainers for your projects, that's good.

**Comment by mrkkrp** [comment]
Don't forget to update metadata for quicklisp! (The same for `cl-ansi-term`.)
